# Generated by Django 2.2.2 on 2019-06-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
